[workspace]
members = [
    "application",
    "kernel",
    "driver",
    "server"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["turtton"]

[workspace.dependencies]
async-trait = "0.1.74"